### ISSUE TITLE
Error: Resource for parameter [deviceId] is not found

### ISSUE THREAD

**Issue by nimosunbit** [tylerlong/ringcentral-softphone-js#3] opened 2020-05-04 05:55 UTC
Hey,

I am trying to use one of my users to register a softphone and getting this error:
`Error: Resource for parameter [deviceId] is not found`

**Comment by tylerlong** [comment] 2020-05-13 21:10
Could you please post more details? Such as stack trace? 

Any instructions to reproduce the issue?

**Comment by nimosunbit** [comment] 2020-05-14 05:27
This is the only error I get. I think it relates to specific extensions. When I switched the supervisor, it worked.

**Comment by tylerlong** [comment] 2020-05-17 03:25
Close it since no reliable way to reproduce.

**Closed as completed by tylerlong** 2020-05-17 03:25 UTC
